apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
    used-by: {{ template "fullname" . }}-nginx
data:
  nginx.conf: |
    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }
    server {
            listen 80 default_server;
            listen [::]:80 default_server ipv6only=on;
            
            root /usr/share/nginx/html;
            index index.html index.htm;

            # static file 404's aren't logged and expires header is set to maximum age
            location ~* \.(jpg|jpeg|gif|css|png|js|ico|html)$ {
              access_log off;
              expires max;
            }

            location ~ /\.ht {
              deny  all;
            }

            location ~* /api {
              proxy_pass http://127.0.0.1:8001;
          }
      }
